// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bgs/low/pb/client/global_extensions/method_options.proto

#include "method_options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BGSMethodOptions;
}  // namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto
namespace bgs {
namespace protocol {
class BGSMethodOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BGSMethodOptions>
      _instance;
} _BGSMethodOptions_default_instance_;
}  // namespace protocol
}  // namespace bgs
namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto {
static void InitDefaultsBGSMethodOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bgs::protocol::_BGSMethodOptions_default_instance_;
    new (ptr) ::bgs::protocol::BGSMethodOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bgs::protocol::BGSMethodOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BGSMethodOptions =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBGSMethodOptions}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BGSMethodOptions.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::BGSMethodOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::BGSMethodOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::BGSMethodOptions, id_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::bgs::protocol::BGSMethodOptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::bgs::protocol::_BGSMethodOptions_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "bgs/low/pb/client/global_extensions/method_options.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n8bgs/low/pb/client/global_extensions/me"
      "thod_options.proto\022\014bgs.protocol\032 google"
      "/protobuf/descriptor.proto\"\036\n\020BGSMethodO"
      "ptions\022\n\n\002id\030\001 \001(\r:X\n\016method_options\022\036.g"
      "oogle.protobuf.MethodOptions\030\220\277\005 \001(\0132\036.b"
      "gs.protocol.BGSMethodOptionsB%\n\rbnet.pro"
      "tocolB\022MethodOptionsProtoH\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 267);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bgs/low/pb/client/global_extensions/method_options.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto
namespace bgs {
namespace protocol {

// ===================================================================

void BGSMethodOptions::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BGSMethodOptions::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BGSMethodOptions::BGSMethodOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto::scc_info_BGSMethodOptions.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.BGSMethodOptions)
}
BGSMethodOptions::BGSMethodOptions(const BGSMethodOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.BGSMethodOptions)
}

void BGSMethodOptions::SharedCtor() {
  id_ = 0u;
}

BGSMethodOptions::~BGSMethodOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.BGSMethodOptions)
  SharedDtor();
}

void BGSMethodOptions::SharedDtor() {
}

void BGSMethodOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BGSMethodOptions::descriptor() {
  ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BGSMethodOptions& BGSMethodOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto::scc_info_BGSMethodOptions.base);
  return *internal_default_instance();
}


void BGSMethodOptions::Swap(BGSMethodOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BGSMethodOptions::InternalSwap(BGSMethodOptions* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata BGSMethodOptions::GetMetadata() const {
  protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fmethod_5foptions_2eproto::file_level_metadata[kIndexInFileMessages];
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::BGSMethodOptions >, 11, false >
  method_options(kMethodOptionsFieldNumber, *::bgs::protocol::BGSMethodOptions::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace bgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bgs::protocol::BGSMethodOptions* Arena::CreateMaybeMessage< ::bgs::protocol::BGSMethodOptions >(Arena* arena) {
  return Arena::CreateInternal< ::bgs::protocol::BGSMethodOptions >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
