// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bgs/low/pb/client/global_extensions/service_options.proto

#ifndef PROTOBUF_INCLUDED_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto
#define PROTOBUF_INCLUDED_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto 

namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto
namespace bgs {
namespace protocol {
class BGSServiceOptions;
class BGSServiceOptionsDefaultTypeInternal;
extern BGSServiceOptionsDefaultTypeInternal _BGSServiceOptions_default_instance_;
class SDKServiceOptions;
class SDKServiceOptionsDefaultTypeInternal;
extern SDKServiceOptionsDefaultTypeInternal _SDKServiceOptions_default_instance_;
}  // namespace protocol
}  // namespace bgs
namespace google {
namespace protobuf {
template<> ::bgs::protocol::BGSServiceOptions* Arena::CreateMaybeMessage<::bgs::protocol::BGSServiceOptions>(Arena*);
template<> ::bgs::protocol::SDKServiceOptions* Arena::CreateMaybeMessage<::bgs::protocol::SDKServiceOptions>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bgs {
namespace protocol {

// ===================================================================

class BGSServiceOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bgs.protocol.BGSServiceOptions) */ {
 public:
  BGSServiceOptions();
  virtual ~BGSServiceOptions();

  BGSServiceOptions(const BGSServiceOptions& from);

  inline BGSServiceOptions& operator=(const BGSServiceOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BGSServiceOptions(BGSServiceOptions&& from) noexcept
    : BGSServiceOptions() {
    *this = ::std::move(from);
  }

  inline BGSServiceOptions& operator=(BGSServiceOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BGSServiceOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BGSServiceOptions* internal_default_instance() {
    return reinterpret_cast<const BGSServiceOptions*>(
               &_BGSServiceOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BGSServiceOptions* other);
  friend void swap(BGSServiceOptions& a, BGSServiceOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BGSServiceOptions* New() const final {
    return CreateMaybeMessage<BGSServiceOptions>(NULL);
  }

  BGSServiceOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BGSServiceOptions>(arena);
  }
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BGSServiceOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string descriptor_name = 1;
  bool has_descriptor_name() const;
  void clear_descriptor_name();
  static const int kDescriptorNameFieldNumber = 1;
  const ::std::string& descriptor_name() const;
  void set_descriptor_name(const ::std::string& value);
  #if LANG_CXX11
  void set_descriptor_name(::std::string&& value);
  #endif
  void set_descriptor_name(const char* value);
  void set_descriptor_name(const char* value, size_t size);
  ::std::string* mutable_descriptor_name();
  ::std::string* release_descriptor_name();
  void set_allocated_descriptor_name(::std::string* descriptor_name);

  // @@protoc_insertion_point(class_scope:bgs.protocol.BGSServiceOptions)
 private:
  void set_has_descriptor_name();
  void clear_has_descriptor_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr descriptor_name_;
  friend struct ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SDKServiceOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bgs.protocol.SDKServiceOptions) */ {
 public:
  SDKServiceOptions();
  virtual ~SDKServiceOptions();

  SDKServiceOptions(const SDKServiceOptions& from);

  inline SDKServiceOptions& operator=(const SDKServiceOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SDKServiceOptions(SDKServiceOptions&& from) noexcept
    : SDKServiceOptions() {
    *this = ::std::move(from);
  }

  inline SDKServiceOptions& operator=(SDKServiceOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SDKServiceOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SDKServiceOptions* internal_default_instance() {
    return reinterpret_cast<const SDKServiceOptions*>(
               &_SDKServiceOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SDKServiceOptions* other);
  friend void swap(SDKServiceOptions& a, SDKServiceOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SDKServiceOptions* New() const final {
    return CreateMaybeMessage<SDKServiceOptions>(NULL);
  }

  SDKServiceOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SDKServiceOptions>(arena);
  }
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SDKServiceOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool inbound = 1;
  bool has_inbound() const;
  void clear_inbound();
  static const int kInboundFieldNumber = 1;
  bool inbound() const;
  void set_inbound(bool value);

  // optional bool outbound = 2;
  bool has_outbound() const;
  void clear_outbound();
  static const int kOutboundFieldNumber = 2;
  bool outbound() const;
  void set_outbound(bool value);

  // @@protoc_insertion_point(class_scope:bgs.protocol.SDKServiceOptions)
 private:
  void set_has_inbound();
  void clear_has_inbound();
  void set_has_outbound();
  void clear_has_outbound();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  bool inbound_;
  bool outbound_;
  friend struct ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::TableStruct;
};
// ===================================================================

static const int kServiceOptionsFieldNumber = 90000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::BGSServiceOptions >, 11, false >
  service_options;
static const int kSdkServiceOptionsFieldNumber = 90001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::SDKServiceOptions >, 11, false >
  sdk_service_options;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BGSServiceOptions

// optional string descriptor_name = 1;
inline bool BGSServiceOptions::has_descriptor_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BGSServiceOptions::set_has_descriptor_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BGSServiceOptions::clear_has_descriptor_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BGSServiceOptions::clear_descriptor_name() {
  descriptor_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_descriptor_name();
}
inline const ::std::string& BGSServiceOptions::descriptor_name() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.BGSServiceOptions.descriptor_name)
  return descriptor_name_.GetNoArena();
}
inline void BGSServiceOptions::set_descriptor_name(const ::std::string& value) {
  set_has_descriptor_name();
  descriptor_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bgs.protocol.BGSServiceOptions.descriptor_name)
}
#if LANG_CXX11
inline void BGSServiceOptions::set_descriptor_name(::std::string&& value) {
  set_has_descriptor_name();
  descriptor_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bgs.protocol.BGSServiceOptions.descriptor_name)
}
#endif
inline void BGSServiceOptions::set_descriptor_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_descriptor_name();
  descriptor_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bgs.protocol.BGSServiceOptions.descriptor_name)
}
inline void BGSServiceOptions::set_descriptor_name(const char* value, size_t size) {
  set_has_descriptor_name();
  descriptor_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bgs.protocol.BGSServiceOptions.descriptor_name)
}
inline ::std::string* BGSServiceOptions::mutable_descriptor_name() {
  set_has_descriptor_name();
  // @@protoc_insertion_point(field_mutable:bgs.protocol.BGSServiceOptions.descriptor_name)
  return descriptor_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BGSServiceOptions::release_descriptor_name() {
  // @@protoc_insertion_point(field_release:bgs.protocol.BGSServiceOptions.descriptor_name)
  if (!has_descriptor_name()) {
    return NULL;
  }
  clear_has_descriptor_name();
  return descriptor_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BGSServiceOptions::set_allocated_descriptor_name(::std::string* descriptor_name) {
  if (descriptor_name != NULL) {
    set_has_descriptor_name();
  } else {
    clear_has_descriptor_name();
  }
  descriptor_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), descriptor_name);
  // @@protoc_insertion_point(field_set_allocated:bgs.protocol.BGSServiceOptions.descriptor_name)
}

// -------------------------------------------------------------------

// SDKServiceOptions

// optional bool inbound = 1;
inline bool SDKServiceOptions::has_inbound() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SDKServiceOptions::set_has_inbound() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SDKServiceOptions::clear_has_inbound() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SDKServiceOptions::clear_inbound() {
  inbound_ = false;
  clear_has_inbound();
}
inline bool SDKServiceOptions::inbound() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.SDKServiceOptions.inbound)
  return inbound_;
}
inline void SDKServiceOptions::set_inbound(bool value) {
  set_has_inbound();
  inbound_ = value;
  // @@protoc_insertion_point(field_set:bgs.protocol.SDKServiceOptions.inbound)
}

// optional bool outbound = 2;
inline bool SDKServiceOptions::has_outbound() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SDKServiceOptions::set_has_outbound() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SDKServiceOptions::clear_has_outbound() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SDKServiceOptions::clear_outbound() {
  outbound_ = false;
  clear_has_outbound();
}
inline bool SDKServiceOptions::outbound() const {
  // @@protoc_insertion_point(field_get:bgs.protocol.SDKServiceOptions.outbound)
  return outbound_;
}
inline void SDKServiceOptions::set_outbound(bool value) {
  set_has_outbound();
  outbound_ = value;
  // @@protoc_insertion_point(field_set:bgs.protocol.SDKServiceOptions.outbound)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace bgs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto
