// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bgs/low/pb/client/global_extensions/service_options.proto

#include "service_options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BGSServiceOptions;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SDKServiceOptions;
}  // namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto
namespace bgs {
namespace protocol {
class BGSServiceOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BGSServiceOptions>
      _instance;
} _BGSServiceOptions_default_instance_;
class SDKServiceOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SDKServiceOptions>
      _instance;
} _SDKServiceOptions_default_instance_;
}  // namespace protocol
}  // namespace bgs
namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto {
static void InitDefaultsBGSServiceOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bgs::protocol::_BGSServiceOptions_default_instance_;
    new (ptr) ::bgs::protocol::BGSServiceOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bgs::protocol::BGSServiceOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BGSServiceOptions =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBGSServiceOptions}, {}};

static void InitDefaultsSDKServiceOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bgs::protocol::_SDKServiceOptions_default_instance_;
    new (ptr) ::bgs::protocol::SDKServiceOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bgs::protocol::SDKServiceOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SDKServiceOptions =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSDKServiceOptions}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BGSServiceOptions.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SDKServiceOptions.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::BGSServiceOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::BGSServiceOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::BGSServiceOptions, descriptor_name_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::SDKServiceOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::SDKServiceOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::SDKServiceOptions, inbound_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bgs::protocol::SDKServiceOptions, outbound_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::bgs::protocol::BGSServiceOptions)},
  { 7, 14, sizeof(::bgs::protocol::SDKServiceOptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::bgs::protocol::_BGSServiceOptions_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bgs::protocol::_SDKServiceOptions_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "bgs/low/pb/client/global_extensions/service_options.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n9bgs/low/pb/client/global_extensions/se"
      "rvice_options.proto\022\014bgs.protocol\032 googl"
      "e/protobuf/descriptor.proto\",\n\021BGSServic"
      "eOptions\022\027\n\017descriptor_name\030\001 \001(\t\"6\n\021SDK"
      "ServiceOptions\022\017\n\007inbound\030\001 \001(\010\022\020\n\010outbo"
      "und\030\002 \001(\010:[\n\017service_options\022\037.google.pr"
      "otobuf.ServiceOptions\030\220\277\005 \001(\0132\037.bgs.prot"
      "ocol.BGSServiceOptions:_\n\023sdk_service_op"
      "tions\022\037.google.protobuf.ServiceOptions\030\221"
      "\277\005 \001(\0132\037.bgs.protocol.SDKServiceOptionsB"
      "&\n\rbnet.protocolB\023ServiceOptionsProtoH\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 439);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bgs/low/pb/client/global_extensions/service_options.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto
namespace bgs {
namespace protocol {

// ===================================================================

void BGSServiceOptions::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BGSServiceOptions::kDescriptorNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BGSServiceOptions::BGSServiceOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::scc_info_BGSServiceOptions.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.BGSServiceOptions)
}
BGSServiceOptions::BGSServiceOptions(const BGSServiceOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  descriptor_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_descriptor_name()) {
    descriptor_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.descriptor_name_);
  }
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.BGSServiceOptions)
}

void BGSServiceOptions::SharedCtor() {
  descriptor_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

BGSServiceOptions::~BGSServiceOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.BGSServiceOptions)
  SharedDtor();
}

void BGSServiceOptions::SharedDtor() {
  descriptor_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BGSServiceOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BGSServiceOptions::descriptor() {
  ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BGSServiceOptions& BGSServiceOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::scc_info_BGSServiceOptions.base);
  return *internal_default_instance();
}


void BGSServiceOptions::Swap(BGSServiceOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BGSServiceOptions::InternalSwap(BGSServiceOptions* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata BGSServiceOptions::GetMetadata() const {
  protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SDKServiceOptions::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SDKServiceOptions::kInboundFieldNumber;
const int SDKServiceOptions::kOutboundFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SDKServiceOptions::SDKServiceOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::scc_info_SDKServiceOptions.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bgs.protocol.SDKServiceOptions)
}
SDKServiceOptions::SDKServiceOptions(const SDKServiceOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&inbound_, &from.inbound_,
    static_cast<size_t>(reinterpret_cast<char*>(&outbound_) -
    reinterpret_cast<char*>(&inbound_)) + sizeof(outbound_));
  // @@protoc_insertion_point(copy_constructor:bgs.protocol.SDKServiceOptions)
}

void SDKServiceOptions::SharedCtor() {
  ::memset(&inbound_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&outbound_) -
      reinterpret_cast<char*>(&inbound_)) + sizeof(outbound_));
}

SDKServiceOptions::~SDKServiceOptions() {
  // @@protoc_insertion_point(destructor:bgs.protocol.SDKServiceOptions)
  SharedDtor();
}

void SDKServiceOptions::SharedDtor() {
}

void SDKServiceOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SDKServiceOptions::descriptor() {
  ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SDKServiceOptions& SDKServiceOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::scc_info_SDKServiceOptions.base);
  return *internal_default_instance();
}


void SDKServiceOptions::Swap(SDKServiceOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SDKServiceOptions::InternalSwap(SDKServiceOptions* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SDKServiceOptions::GetMetadata() const {
  protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bgs_2flow_2fpb_2fclient_2fglobal_5fextensions_2fservice_5foptions_2eproto::file_level_metadata[kIndexInFileMessages];
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::BGSServiceOptions >, 11, false >
  service_options(kServiceOptionsFieldNumber, *::bgs::protocol::BGSServiceOptions::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::bgs::protocol::SDKServiceOptions >, 11, false >
  sdk_service_options(kSdkServiceOptionsFieldNumber, *::bgs::protocol::SDKServiceOptions::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace bgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bgs::protocol::BGSServiceOptions* Arena::CreateMaybeMessage< ::bgs::protocol::BGSServiceOptions >(Arena* arena) {
  return Arena::CreateInternal< ::bgs::protocol::BGSServiceOptions >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bgs::protocol::SDKServiceOptions* Arena::CreateMaybeMessage< ::bgs::protocol::SDKServiceOptions >(Arena* arena) {
  return Arena::CreateInternal< ::bgs::protocol::SDKServiceOptions >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
